version: '3.4'

services:
  api:
    container_name: ites.server
    image: itesserver
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
    build:
      context: .
      dockerfile: ./ites.Server/Dockerfile
    networks:
      - ites
    depends_on:
      - db

  db:
    container_name: ites.db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: itesdb
      POSTGRES_USER: gurori
      POSTGRES_PASSWORD: Egorzak_21
    networks:
      - ites
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  ites:
    driver: bridge

volumes:
  postgres-data:
