services:
  api:
    container_name: ites.server
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - app
      - database
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    container_name: ites.db
    image: postgres:18
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ites -d itesdb"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - database
    volumes:
      - postgres_data:/var/lib/postgresql

networks:
  app:
    driver: bridge
  database:
    driver: bridge

volumes:
  postgres_data:
