<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ites.Application\ites.Application.csproj" />
    <ProjectReference Include="..\ites.Core\ites.Core.csproj" />
    <ProjectReference Include="..\ites.DataAccess\ites.DataAccess.csproj" />
  </ItemGroup>

</Project>
