#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ites.Server/ites.Server.csproj", "ites.Server/"]
RUN dotnet restore "./ites.Server/ites.Server.csproj"
COPY . .
WORKDIR "/src/ites.Server"
RUN dotnet build "./ites.Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./ites.Server.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ites.Server.dll"]
